config/routes.rb
Shareabouts::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do
    get 'sign_in', :to => 'users/sessions#new', :as => :new_user_session
    get 'sign_out', :to => 'users/sessions#destroy', :as => :destroy_user_session
  end
  
  devise_for :admins, :path => "authmin" # silly path due to conflict with rails_admin path

  match '/locations/:feature_point_id/votes', :controller => 'votes', :action => 'options', :constraints => {:method => 'OPTIONS'}
  
  resources :feature_points, :path => 'locations', :only => [:new, :create, :edit, :update, :index, :show, :update] do
    resources :votes, :only => [:create, :destroy]
    
    resources :comments, :only => [:create, :new]
    collection do
      get 'within_region'
      get 'events'
    end
    member do
      get 'share'
    end
  end
    
  resources :feature_polygons, :path => 'areas', :only => [:index]
  
  resources :regions, :only => [:index] do
    collection do
      get 'import', :as => :import
      post 'upload', :as => :upload, :path => 'import'
    end
  end
  
  resources :pages, :only => [:show]
  resources :activity, :only => [:index]
  
  match "regions/import", :to => "regions#import", :via => :get, :as => :import_regions
  match "regions/import", :to => "regions#upload", :via => :post, :as => :upload_regions
  
  root :to => 'feature_points#index'
end

app/views/shared/_account.html.erb
<div class="account">
  <div class="my-points">
    <div><%= t "account.my_points" -%></div>
    <span><%= current_user.feature_points.count -%> </span>
  </div>
  <div class="my-supports">
    <div><%= t "account.my_supports" -%></div>
    <span><%= current_user.votes.count -%></span>
  </div>
</div>

<ul class="menu">
  <li><%= avatar_for current_user %><span class="arrow-s"></span></li>
  <li><%= link_to "Sign out", destroy_user_session_path %></li>
</ul>

app/views/shared/_discussion.html.erb
<% if commentable.comments.count > 0 %>
<div class="comments">
  <div class="discussion-header">
    <h3><%= t "feature.comment.header" %></h3>
    <div class="comment-count">
      <%= pluralize commentable.comments.count, t("feature.comment.label") %>
    </div>
  </div>
  <ul>
    <% for comment in commentable.comments %>
      <li class="clearfix">
        <div class="comment">
          <p class="meta">
            <%= comment.submitter_name %>, 
            on <%= comment.created_at.strftime("%B %-d, %Y") %> 
            at <%= comment.created_at.strftime("%l:%M %P") %>
          </p>
          <p class="body">
            <%= comment.comment %>
          </p>
        </div>
      </li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_flashes.html.erb
<% if flash[:notice] %>
  <div class="flash notice">
    <%= flash[:notice] %>
  </div>
<% end %>
<% if flash[:error] %>
  <div class="flash error">
    <%= flash[:error] %>
  </div>
<% end %>

app/views/shared/_javascript_options.html.erb
<%# 
  # Applying SiteOptions and other Admin settings to javascript. 
  # It's important for this to live outside of an asset-pipeline-affected asset, 
  # or else the app will require recompilation when the options are updated.
%>

<script type="text/javascript" charset="utf-8">
  if (!window.shareabouts) window.shareabouts = {};
  
  window.shareabouts.map_initial_zoom = <%= SiteOption["map_initial_zoom"].try(:value) || 13 %>;
  window.shareabouts.map_max_zoom = <%= SiteOption["map_max_zoom"].try(:value) || 18 %>;
  window.shareabouts.map_min_zoom = <%= SiteOption["map_min_zoom"].try(:value) || 0 %>;
  
  <% if SiteOption.bounds? %>
    window.shareabouts.map_bounds = new L.LatLngBounds(
      new L.LatLng(<%= SiteOption["map_bounds_p1_lat"].value %>, <%= SiteOption["map_bounds_p1_long"].value %>), 
      new L.LatLng(<%= SiteOption["map_bounds_p2_lat"].value %>, <%= SiteOption["map_bounds_p2_long"].value %>)
    );
  <% end %>
  
  <% if SiteOption.center? %>
    window.shareabouts.map_center = new L.LatLng(<%= SiteOption["map_center_lat"].value %>, <%= SiteOption["map_center_long"].value %>);
  <% end %>
  
  // Custom marker Icons for location types with markers
  window.shareabouts.LocationTypeIcons = {
    <%= Marker.all.map(&:location_type).map do |location_type|
      <<-js
      #{location_type.name.parameterize.underscore} : L.Icon.extend({
        iconUrl     : '#{ path_to_url location_type.image.url(:original) }',
      	iconSize    : new L.Point(#{location_type.marker.icon_width}, #{location_type.marker.icon_height}),
      	iconAnchor  : new L.Point(#{location_type.marker.icon_anchor_x}, #{location_type.marker.icon_anchor_y}),
      	popupAnchor : new L.Point(#{location_type.marker.popup_anchor_x}, #{location_type.marker.popup_anchor_y}),
        shadowSize  : new L.Point(36, 34),
        shadowUrl   : '#{ image_url("marker-shadow.png") }'
      })
      js
    end.map(&:strip).join(",\n") %>
  };
  
  <% if @winners.present? %>
    window.shareabouts.winners = [<%= @winners.map(&:id).join ", " %>];
  <% end %>
  
  // full paths to things
  window.shareabouts.urls = {
    marker_icon :        '<%= image_url("feature-point.png") %>',
    focused_marker_icon : '<%= image_url("marker-focused.png") %>',
    shadow_icon :         '<%= image_url("marker-shadow.png") %>',
    new_marker_icon :     '<%= image_url("marker-plus.png") %>',
    crosshair_icon :      '<%= image_url("crosshair.png") %>',
    feature_points_url :       '<%= feature_points_url campaign_params %>',
    feature_point_url :        '<%= feature_point_url("FEATURE_ID", campaign_params) %>',
    new_feature_point_url :    '<%= new_feature_point_url campaign_params %>'
  }
  
</script>

<% if SiteOption["google_analytics_code"].try(:value).present? %>
  <!-- Google Analytics Code Start -->
  <%= SiteOption["google_analytics_code"].value.html_safe %>
  <!-- END Google Analytics Code -->
<% end %>

app/views/shared/_share.html.erb
<p class="message"><%= message %></p>
<ul class="share_links">
  <li class="facebook">
    <%= link_to "recommend on facebook", "https://www.facebook.com/sharer/sharer.php?u=UPDATE_URL", 
      :class => "facebook", 
      :target => "_blank" -%>
  </li>
  <li class="twitter">
    <%= link_to "tweet it", 
      "https://twitter.com/intent/tweet?source=webclient&text=#{ t("feature.sharing.twitter.status", :url => "UPDATE_URL") }", 
      :class => "twitter", 
      :target => "_blank" -%>
  </li>
  <li class="email">
    <%= mail_to "", "email", 
      :subject => t("feature.sharing.email.subject"), 
      :body => t("feature.sharing.email.body", :url => "UPDATE_URL"), 
      :class => "email" -%>
  </li>
</ul>

<script type="text/javascript" charset="utf-8">
 jQuery(function($){
   var share_url = [ window.parent.location.href.split("#")[0], "%23locations/<%= shareable.id %>"].join("");
   $(".share_links a").each(function(){
     var link = $(this);
     link.attr("href", link.attr("href").replace("UPDATE_URL", share_url));
   });
 });
</script>

app/views/shared/_sign_in.html.erb
<%= link_to t("auth.fb_signin"), user_omniauth_authorize_path(:facebook), :class => 'facebook-login sign-in' %>
<%= link_to t("auth.twitter_signin"), user_omniauth_authorize_path(:twitter), :class => 'twitter-login sign-in' %>

app/views/shared/_signed_in.html.erb
Signed in as <strong><%= current_user.name %></strong>. 
<%= link_to "Sign out", destroy_user_session_path %>