config/routes.rb
Shareabouts::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do
    get 'sign_in', :to => 'users/sessions#new', :as => :new_user_session
    get 'sign_out', :to => 'users/sessions#destroy', :as => :destroy_user_session
  end
  
  devise_for :admins, :path => "authmin" # silly path due to conflict with rails_admin path

  match '/locations/:feature_point_id/votes', :controller => 'votes', :action => 'options', :constraints => {:method => 'OPTIONS'}
  
  resources :feature_points, :path => 'locations', :only => [:new, :create, :edit, :update, :index, :show, :update] do
    resources :votes, :only => [:create, :destroy]
    
    resources :comments, :only => [:create, :new]
    collection do
      get 'within_region'
      get 'events'
    end
    member do
      get 'share'
    end
  end
    
  resources :feature_polygons, :path => 'areas', :only => [:index]
  
  resources :regions, :only => [:index] do
    collection do
      get 'import', :as => :import
      post 'upload', :as => :upload, :path => 'import'
    end
  end
  
  resources :pages, :only => [:show]
  resources :activity, :only => [:index]
  
  match "regions/import", :to => "regions#import", :via => :get, :as => :import_regions
  match "regions/import", :to => "regions#upload", :via => :post, :as => :upload_regions
  
  root :to => 'feature_points#index'
end

app/controllers/activity_controller.rb
class ActivityController < ApplicationController

  def index
    # authorize_for_domains

    where = if params[:after].present?
      ["id > ?", params[:after]]
    else
      ""
    end
        
    @activity_items = ActivityItem.for_campaign(@campaign).where(where)
      .limit(params[:limit])
      .order('created_at desc')
    
    render :json => {
      :vote_count => "#{Vote.for_campaign(@campaign).visible.count} actions",
      :view       => render_to_string(:partial => "index.html")
    }.to_json
  end
end

app/views/activity/_comment.html.erb
<a href="<%= feature_point_path(activity_item.subject_parent) %>">
  <strong><%= activity_item.user_name %></strong> 
  <%= t("activity.comment.action") %> 
  <%= activity_item.description %>: 
  &ldquo;<%= truncate activity_item.subject.comment, :length => 25 %>&rdquo;
</a>

app/views/activity/_feature_point.html.erb
<a href="<%= feature_point_path(activity_item.subject) %>">
  <strong><%= activity_item.user_name %></strong> 
  <%= t("activity.point.action") %> 
  <%= t("activity.point.indefinite_article")%>
  <%= FeaturePoint.model_name.human %> 
  <%= t("activity.point.in_region", :region => activity_item.region.name) if activity_item.region.present? %>
</a>

app/views/activity/_index.html.erb
<% @activity_items.each do |activity_item| %>
  <% if activity_item.subject_parent.visible? %>
    <li class="clearfix <%= activity_item.subject_parent.location_type.name.gsub(/ /, "").downcase %>" data-id="<%= activity_item.id %>" data-feature-id="<%= activity_item.feature.id %>">
      <a href="#">
        <strong><%= activity_item.user_name %></strong> 
        <%= t "activity.vote", :location => activity_item.subject_parent.name %>
      </a>
    </li>
  <% end %>
<% end %>

app/views/activity/_vote.html.erb
<a href="<%= feature_point_path(activity_item.subject_parent) %>">
  <strong><%= activity_item.user_name %></strong> 
  <%= t("activity.vote.action") %> 
  <%= activity_item.description %> 
  <%= t("activity.point.in_region", :region => activity_item.region.name) if activity_item.region.present? %>
</a>

app/views/activity/index.html.erb
<% @activity_items.each do |activity_item| %>
<li class="clearfix" data-id="<%= activity_item.id %>" data-feature-id="<%= activity_item.feature.id %>">
  <div class="avatar">
    <%= avatar_for(activity_item.user) if activity_item.user.present? %>
    <div class="badge <%= activity_item.subject_type.underscore %>"></div>
  </div>
  <%= render "#{activity_item.subject_type.underscore}.html", :activity_item => activity_item  %>
</li>
<% end %>