config/routes.rb
Shareabouts::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do
    get 'sign_in', :to => 'users/sessions#new', :as => :new_user_session
    get 'sign_out', :to => 'users/sessions#destroy', :as => :destroy_user_session
  end
  
  devise_for :admins, :path => "authmin" # silly path due to conflict with rails_admin path

  match '/locations/:feature_point_id/votes', :controller => 'votes', :action => 'options', :constraints => {:method => 'OPTIONS'}
  
  resources :feature_points, :path => 'locations', :only => [:new, :create, :edit, :update, :index, :show, :update] do
    resources :votes, :only => [:create, :destroy]
    
    resources :comments, :only => [:create, :new]
    collection do
      get 'within_region'
      get 'events'
    end
    member do
      get 'share'
    end
  end
    
  resources :feature_polygons, :path => 'areas', :only => [:index]
  
  resources :regions, :only => [:index] do
    collection do
      get 'import', :as => :import
      post 'upload', :as => :upload, :path => 'import'
    end
  end
  
  resources :pages, :only => [:show]
  resources :activity, :only => [:index]
  
  match "regions/import", :to => "regions#import", :via => :get, :as => :import_regions
  match "regions/import", :to => "regions#upload", :via => :post, :as => :upload_regions
  
  root :to => 'feature_points#index'
end

app/models/feature_point.rb
# FeaturePoint represents a point that is displayed on the map.
# If there are any Regions, which are created by an Admin uploading a 
# shapefile, points must fall within at least one of those regions to be valid.
# FeaturePoints can be marked as being not visible in the admin section.
# When a FeaturePoint is marked as not visible, its associated activity items
# are deleted.

class FeaturePoint < ActiveRecord::Base

  class InRegionValidator < ActiveModel::Validator
    def validate(record)
      record.find_regions[0]
    rescue IndexError
      record.errors[:the_geom] << I18n.t("feature.notice.out_of_bounds")
    end
  end

  attr_accessor :found_regions

  scope :visible, where(:visible => true)
  scope :for_campaign, lambda { |campaign| where(:campaign_id => campaign.id) }
  
  has_attached_file :image, :styles => { :thumb => "120x90#" }

  belongs_to :admin, :foreign_key => :user_id
  belongs_to :profile
  belongs_to :location_type
  belongs_to :campaign
  has_many :votes, :as => :supportable, :dependent => :destroy
  has_many :comments, :as => :commentable, :dependent => :destroy, :inverse_of => :commentable
  has_many :feature_regions, :as => :feature, :dependent => :destroy
  has_many :regions, :through => :feature_regions
  has_many :activity_items, :as => :subject, :inverse_of => :subject, :dependent => :destroy
  has_many :children_activity_items, :as => :subject_parent, :class_name => "ActivityItem", :dependent => :destroy
  has_one :user, :through => :profile
  has_one :marker, :through => :location_type
  
  # deprecated
  has_one :feature_location_type, :as => :feature, :dependent => :destroy, :inverse_of => :feature
  
  before_save :set_visible
  before_create :find_regions
  after_create :add_to_regions
  after_create :create_vote
  after_update :maybe_remove_activity_items

  accepts_nested_attributes_for :feature_location_type
  
  before_validation :set_event_date_year

  validates :campaign, :presence => true
  validates :name, :presence => true
  validates :description, :presence => true
  validates :location_type, :presence => true

  validates :event_link, :format => {:with => URI::regexp(%w(http https)), :message => "should be a valid URL", :allow_blank => true }

  validates :address, :presence => true, :if => "campaign.enable_events?"
  validates :event_date, :presence => true, :weekend => {:allow_blank => true}, :if => "campaign.enable_events?"
  validates :event_start_time, :presence => true, :if => "campaign.enable_events?"
  validates :event_end_time, :presence => true, :if => "campaign.enable_events?"
  
  validates_with TimeOrderValidator
  
  validates :the_geom,  :presence => true
  validates_with InRegionValidator, :if => lambda { Region.any? }

  # Returns points which are visible within the boundaries
  def self.visible_within(corners)
    visible.where( ["ST_Contains(ST_GeomFromText('POLYGON((? ?,? ?,? ?,? ?,? ?))',4326), feature_points.the_geom)",
      corners[0][0], corners[0][1], corners[1][0], corners[0][1], corners[1][0], corners[1][1], corners[0][0], corners[1][1], corners[0][0], corners[0][1]]
    )
  end
  
  def winner?
    location_type.name.match(/Winner/).present?
  end
  
  def set_event_date_year
    self.event_date = Date.new Date.today.year, event_date.month, event_date.day if event_date.present?
  end
  
  def display_event_time
    return "" unless event_date && event_start_time && event_end_time
    "#{event_date.strftime "%A %B %-d, %Y"}, #{event_start_time.strftime "%-l%P"}-#{event_end_time.strftime "%-l%P"}"
  end

  def latitude
    return the_geom.y if the_geom
  end

  def longitude
    return the_geom.x if the_geom
  end

  def display_name
    name.present? ? name : display_the_geom
  end

  def display_the_geom
    "(#{sprintf('%.6f', latitude)}, #{sprintf('%.6f', longitude)})"
  end

  def display_submitter
    profile.try(:name) || (submitter_name.present? ? submitter_name : User.model_name.human.capitalize)
  end
  
  def region
    regions.find(&:default?) || regions.first
  end
  
  def support_count
    votes.count
  end
  
  def as_json
    attrs = { :id => id, :lat => latitude, :lon => longitude, :pop => support_count }
    attrs[:location_type] = location_type.name.parameterize.underscore if marker.present?
    attrs
  end

  def as_geo_json
    {
      :type => "Feature",
      :geometry => {
        :type => "Point",
        :coordinates => [longitude, latitude]
      },
      :properties => {
        :id             => id,
        :name           => name,
        :description    => description,
        :location_type  => location_type
      }
    }
  end

  def find_regions
    return [] unless latitude && longitude
    @found_regions ||= ActiveRecord::Base.connection.execute( "select * from regions where ST_Contains(the_geom, ST_SetSRID(ST_Point(#{longitude.to_f},#{latitude.to_f}),4326))")
  end

  def add_to_regions
    found_regions.each do |row|
      feature_regions.create :region_id => row["id"].to_i
    end
  end

  private
  
  def create_vote
    votes.create :profile => profile, :campaign => campaign
  end

  # Only set to visible if created by an admin (presense of user_id) or if explicitely set
  def set_visible
    if user_id.present?
      self.visible = true
    else
      self.visible = false if !visible
    end
    true
  end
  
  def maybe_remove_activity_items
    return if self.visible?
    
    self.activity_items.delete_all
    self.children_activity_items.delete_all
  end
end

app/controllers/feature_points_controller.rb
class FeaturePointsController < ApplicationController

  before_filter :ignore_feature_location_type_fields_if_empty, :find_or_create_profile, :only => :create  
  before_filter :set_cache_buster, :only => :show # for IE8
  
  def share    
    @feature_point = FeaturePoint.find params[:id]
    
    render :json => {
      :view => render_to_string(:partial => "shared/share.html", :locals => {
        :shareable => @feature_point,
        :message => I18n.t("feature.sharing.after_vote") # we can only get here directly after voting
      })
    }
  end
  
  def index
    respond_to do |format|
      format.html do 
        @winners = FeaturePoint.for_campaign(@campaign).joins(:location_type).where("location_types.winner = true") if @campaign
      end
      format.json do
        @feature_points = FeaturePoint.for_campaign(@campaign).visible.where [ "id > ?", params[:after].to_i ]
        render :json => @feature_points.map(&:as_json)
      end
    end
  end
  
  def events
    # authorize_for_domains
    
    return render :status => :ok if !@campaign || !@campaign.enable_events?
    
    @feature_points = FeaturePoint.for_campaign(@campaign).visible
    
    render :json => {
      :view => render_to_string(:partial => "events.html")
    }
  end
  
  def new
    @feature_point = FeaturePoint.new

    respond_to do |format|
      format.json { render :json => { :view => render_to_string(:partial => "form.html") } }
    end
  end
  
  def create
    authorize! :create, FeaturePoint
    # authorize_for_domains

    @feature_point = FeaturePoint.new params[:feature_point].merge({
      :the_geom => the_geom_from_params(params), 
      :profile => @profile, 
      :campaign => @campaign,
      :user_id => current_admin.try(:id)
    })
    
    set_location_type
    
    if @feature_point.save
      find_and_store_vote @feature_point
      @comment = @feature_point.comments.new :profile => @profile
      response = render_to_string( :partial => "confirm.html", :locals => { 
        :message => I18n.t("feature.comment.after_point_added"), :vote_id => @feature_point.votes.first.id 
      } )
      render upload_response(response, :ok)
    else
      response = render_to_string( :partial => "form.html.erb" )
      render upload_response(response, :error)
    end
  end
  
  def edit
    
  end
  
  def update
    @feature_point = FeaturePoint.for_campaign(@campaign).find params[:id]
    authorize! :update, @feature_point
    
    @feature_point.update_attributes params[:feature_point]

    respond_to do |format|
      format.json do
        render :json => { :status => "error", :view => render_to_string(:partial => "show.html.erb", :locals => { :feature_point => @feature_point }) } 
      end
    end
  end
  
  def show
    # past campaigns?
    @feature_point = FeaturePoint.visible.find params[:id], :include => :comments
    respond_to do |format|
      format.html do
        render :action => 'index'
      end
      format.json do
        render :json => { :view => render_to_string(:partial => "show.html", :locals => { :feature_point => @feature_point }) } 
      end
    end
  end
  
  def within_region
    @feature_point = FeaturePoint.new :the_geom => the_geom_from_params(params)
        
    if !@feature_point.valid? && @feature_point.errors[:the_geom].present?
      respond_to do |format|
        format.json { render :json => { :status => "error", :message => @feature_point.errors[:the_geom].join(". ") } }
      end
    else
      respond_to do |format|
        format.json { render :json => { :status => "ok" } }
      end
    end
  end
  
  private
  
  def set_location_type
    @feature_point.location_type = if current_admin.present? && admin_type = LocationType.for_campaign(@campaign).admin.not_winner.first
      admin_type
    else
      LocationType.for_campaign(@campaign).not_admin.not_winner.first
    end
  end
  
  def find_and_store_vote(feature_point)
    vote = @profile.votes.where(:supportable_id => feature_point.id, :supportable_type => feature_point.class.to_s).first
    store_vote_in_cookie vote
  end
  
  def the_geom_from_params(p)
    Point.from_x_y p[:longitude].to_f, p[:latitude].to_f, 4326
  end
  
  def ignore_feature_location_type_fields_if_empty
    params[:feature_point].delete(:feature_location_type_attributes) if params[:feature_point] && params[:feature_point][:feature_location_type_attributes] && 
      params[:feature_point][:feature_location_type_attributes][:location_type_id].blank?
  end
  
  # def upload_response(view)
  #   <<-HTML
  #   <textarea data-type="application/json">
  #      {view:"#{escape_json(view)}"}
  #   </textarea>
  #   HTML
  def upload_response(view, status=:ok)
    if request.headers["CONTENT_TYPE"].match /multipart/
      {
        :text => "<textarea data-type='application/json'>{view:'#{escape_json view}', status:'#{status}'}</textarea>"
      }
    else
      {
        :json => {:view => view, :status => status }
      }
    end
  end  
end

app/views/feature_points/_admin.html.erb
<%= link_to "Edit point / Moderate comments", path_to_url(rails_admin.edit_path("feature_point", feature_point.id, :c => nil)), :target => "_new" %>

app/views/feature_points/_confirm.html.erb
<div class="feature show">  
  <div id="left" class="column">
    <div class="location_image">
      <%= image_tag path_to_url(@feature_point.image.url(:thumb)) if @feature_point.image.present? %>
    </div>
    
    <!-- <div class="next"><%#= link_to "Go back and edit", edit_feature_point_url(@feature_point) %></div> -->
  </div>
  
  <div id="center" class="column">
    <%= render "info.html", :feature_point => @feature_point %>
  </div>
  
  <div id="right" class="column">
    <%= render "comments/new.html", :message => I18n.t("feature.comment.after_point_added"), :from => :feature_point, :vote_id => vote_id %>
  </div>
  
  <div class="close">
    <%= link_to "Close", "#" %>
  </div>
</div><!-- end div.feature -->

app/views/feature_points/_events.html.erb
<table border="0" cellspacing="0" cellpadding="0">
  <tr>
    <th>Name</th>
    <th>Where?</th>
    <th>When?</th>
    <th></th>
  </tr>
  
  <% for feature_point in @feature_points %>
    <tr>
      <td>
        <p><%= link_to feature_point.name, "#", "data-feature-id" => feature_point.id %></p>
        <p><%= pluralize feature_point.votes.count, t("feature.comment.vote_label") %></p>
      </td>
      <td>
        <p><%= feature_point.address %></p>
      </td>
      <td>
        <p><%= feature_point.event_date.strftime "%A %B %-d, %Y" %></p>
      </td>
      <td>
        <div class="vote-link">
          <%= link_to t("feature.comment.vote_label"), "#", "data-feature-id" => feature_point.id  %>
        </div>
      </td>
    </tr>
  <% end %>
</table>

app/views/feature_points/_form.html.erb
<div class="feature new">

  <% if admin_signed_in? %>
    <div class="feature-admin">
      You're logged in as an admin. This location will be a Mission-Electric location.  
    </div>
  <% end %>
  
  <h2 class="popup-title">
    <%= t "feature.form.header" %>
  </h2>
  
  <div id="left" class="column">
    <div class="description">
      <%= t "feature.form.description" %>
    </div>
  </div>
  
  <%= form_for @feature_point, :url => feature_points_url, :html => { :multipart => true } do |form| %>
    <div id="center" class="column">
      <fieldset>
        <div class="name">
          <%= form.label :name, t("feature.form.title_label"), :class => "required" %>
          <%= form.text_field :name %>
        </div>
        <div class="address">
          <%= form.label :address, t("feature.form.address_label"), :class => "required" %>
          <%= form.text_field :address %>
        </div>
        <div class="description">
          <%= form.label :description, t("feature.form.description_label"), :class => "required" %>
          <%= form.text_area :description %>
        </div>
        <p class="count"><span>100</span> char. left.</p>
        <div class="event_link">
          <%= form.label :event_link, t("feature.form.event_link_label") %>
          <%= form.text_field :event_link %>
        </div>
      </fieldset>
    </div>
  
    <div id="right" class="column">
      <fieldset>
        <div class="image">
          <%= form.label :image, t("feature.form.image_label") %>
          <%= form.file_field :image %>
        </div>
        <div class="event_date_time">
          <div class="event_date">
            <%= form.label :event_date, t("feature.form.day_label"), :class => "required"  %>
            <%= form.date_select :event_date, :discard_year => true, :order => [:month, :day], :prompt => true %>
          </div>
          <div class="event_times">
            <div class="event_start_time">
              <%= form.label :event_start_time, t("feature.form.start_time_label"), :class => "required"  %>
              <%= form.time_select :event_start_time, :ampm => true, :discard_minute => true, :prompt => true %>
            </div>
            <div class="event_end_time">
              <%= form.label :event_end_time, t("feature.form.end_time_label"), :class => "required"  %>
              <%= form.time_select :event_end_time, :ampm => true, :discard_minute => true, :prompt => true %>
            </div>
          </div>
        </div>
      </fieldset>
      <div id="submit_new_location">
        <%= form.submit t("feature.form.submit")%>  
      </div>
    </div>
  <% end %>
  
  <div class="close">
    <%= link_to "Close", "#" %>
  </div>
</div><!-- end div.feature -->

app/views/feature_points/_info.html.erb
<h2>
  <span class="vote-label">
    <%= feature_point.votes.count -%>
  </span> 
  <%= "#{Vote.model_name.human}#{"s" if feature_point.votes.count != 1}" -%>
</h2>
<h1>
  <%= feature_point.name -%>
</h1>
<p>
  <strong><%= feature_point.display_event_time -%></strong>
</p>
<p>
  <strong><%= feature_point.address -%></strong>
</p>
<p>
  <%= feature_point.description -%>
</p>
<p>
  <%= link_to feature_point.event_link if feature_point.event_link.present? -%>
</p>

app/views/feature_points/_show.html.erb
<div class="feature show">

  <% if admin_signed_in? %>
    <div class="feature-admin">
      <%= render "feature_points/admin.html", :feature_point => feature_point %>     
    </div>
  <% end %>
  
  <div id="left" class="column">
    <div class="location_image">
      <%= image_tag path_to_url(feature_point.image.url(:thumb)) if feature_point.image.present? %>
      <% if feature_point.winner? %><span class="winner">Winner<span/><% end %>
    </div>
    
    <div class="support">
      <% if can? :create, Vote %>
        <% if vote = vote_for(feature_point) %>
          <%#= render "votes/delete.html", :supportable => feature_point, :vote => vote %>
        <% else %>
          <div id="vote_link">
            <%= render "votes/new.html", :supportable => feature_point %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
  
  <div id="center" class="column">
    <%= render "info.html", :feature_point => feature_point %>
  </div>
  
  <div id="right" class="column">
    <div class="discussion">
      <%= render "shared/discussion.html", :commentable => feature_point %>
    </div>
  </div>
  
  <div class="close">
    <%= link_to "Close", "#" %>
  </div>
</div><!-- end div.feature -->

app/views/feature_points/index.html.erb
<div id="map-container">
  <div id="map"></div>
  <div id="popup"></div>
</div>

<% content_for :javascript do %>
<script type="text/javascript" charset="utf-8">
  if (!window.shareabouts) window.shareabouts = {};
  <% if @feature_point.present? %>
    window.shareabouts.initialFeatureId = <%= @feature_point.id %>;
  <% end %>
</script>
<% end %>

<% content_for :footer do %>
<div class="alpha60 padding10 center rounded-top">
  <% if can? :create, FeaturePoint %>
  <button type="button" id="locate_feature" title="" style="display:none;">
    <%= t 'map_controls.locate_feature' %> 
    <%= image_tag "marker-new-shadow.png" %>
  </button>
  <% end %>
</div>
<% end %>